---
project_name: go-with-github-workflow

release:
  extra_files:
    - glob: ./bom.json
  github:
    owner: ccojocar
    name: go-with-github-workflow

builds:
  - main : ./
    binary: go-with-github-workflow
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: -X main.Version={{.Version}} -X main.GitTag={{.Tag}} -X main.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0

signs:
- cmd: cosign
  stdin: '{{ .Env.COSIGN_PASSWORD}}'
  args: ["sign-blob", "--key=/tmp/cosign.key", "--output=${signature}", "${artifact}"]
  artifacts: all
