name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Build
        uses: cedrickring/golang-action@1.5.1
        with:
          args: go build .
      - name: Run Tests
        uses: cedrickring/golang-action@1.5.1
        with:
          args: go test -v ./...
      - name: Run Security Scan
        uses: securego/gosec@master
        with:
          args: ./...
